openapi: 3.0.1
info:
  title: SimpleAPI
  description: API do simpleAPI — plataforma para simplificar a adequação à LGPD.
  contact: {}
  version: 1.0.0
servers:
- url: https://simpleapi.com.br/api/v1
paths:
  /status:
    get:
      tags:
      - Status
      summary: Obter o status da API
      description: Retorna uma mensagem simples de status indicando que a API está em execução.
      responses:
        "200":
          description: Status da API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/status.StatusResponse'
        "400":
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/utils.ErrorResponse'
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/utils.ErrorResponse'
components:
  schemas:
    status.StatusResponse:
      type: object
      properties:
        apiStatus:
          type: string
        applicationVersion:
          type: string
        databaseStatus:
          type: string
    utils.ErrorResponse:
      type: object
      properties:
        errorCode:
          type: integer
        message:
          type: string
          example: "Invalid request"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
